<?php
/**
 * @file
 * Custom functionality for a wind 
 * farm database
 */

/**
 * implements hook_help().
 */
 function windfarms_help($path, $arg){
 	switch($path){
 	case 'admin/help#windfarms':{
 		$ret_val = '<h3>'.t('About').'</h3>';
 		$ret_val .= '<p>'.t('The Wind Farms module makes it easy to import information about wind farms').'</p>';
 		return $ret_val;
 	break;
 	}
 } 	
 }

/**
 * Implements hook_permission().
 */
function windfarms_permission(){
	return array(
		'administer wind farms' => array(
			'title' => t('administer wind farm stuff')));

}

/**
 * Implements hook_menu().
 */
function windfarms_menu(){
	$items = array();

	// Admin configuration group.
	$items['admin/config/windfarms'] = array(
		'title' => 'Wind Farms',
		'description' => 'Administer Wind Farms',
		'access arguments' => array('administer wind farms'),
		);

	// Admin configuration - Settings.
	$items['admin/config/windfarms/manage'] = array(
	'title' => 'Wind Farms Settings',
	'description' => 'Administer Wind Farms',
	'access arguments' => array('administer wind farms'),	
	'page callback' => 'drupal_get_form',
	'page arguments' => array('windfarms_admin_settings_form'),

		);
	return $items;
}

/**
 * Implements hook_form().
 */
function windfarms_admin_settings_form($node, &$form_state){
	$form = array();

	$form['overview'] = array(
		'#markup' => t('this ui allows admins to manage general windfarm settings'),
		'#prefix' => '<p>',
		'#suffix' => '</p>',
		);
	$form['windfarms_gmap'] = array(
		'#title' => t('enablge google maps'),
'#description ' => t('when anabled, google maps will be rendered if lat and lon are known'),
'#type' => 'checkbox',
'#default_value' => variable_get('windfarms_gmap',1), 
		);

$form['default_center'] = array(
	'#title' => t('Map Center'),
	'#description' => t('Location of the center of the map of the farms.'),
	'#type' => 'fieldset',
	'#collapsible' => TRUE,
	'#collapsed' => FALSE,
	);

$form['default_center']['windfarms_default_center_lat'] =array(
'#title' => t('Latitude'),
'#description' => t('Signed degreesformat (DDD.ddd)'),
'#type' => 'textfield',
'#default_value' => variable_get('windfarms_default_center_lat',42.91455),
'#required' => TRUE,
	);

$form['default_center']['windfarms_default_center_long'] =array(
'#title' => t('Longitude'),
'#description' => t('Signed degreesformat (DDD.ddd)'),
'#type' => 'textfield',
'#default_value' => variable_get('windfarms_default_center_long',75.569851),
'#required' => TRUE,
	);

$options = range(0,20,1);
$options[0] = t('0 - furthest');
$options[20] = t('20 - closest');

$form['default_center']['windfarms_default_center_zoom'] = array(
'#title' => t('google map zoom'),
'#description' => t('default zoom level between 0 and 20'),
'#type' => 'select',
'#options' => $options,
'#default_value' => variable_get('windfarms_default_center_zoom',8),
'#required' => TRUE,

	);
/*
$form['submit'] = array(
'#type' => 'submit',
'#value' => 'save',
	);
*/
	//return $form;
	return system_settings_form($form);
}

/**
 * Validates Wind Farms admin settings
 */
function windfarms_admin_settings_form_validate($form, &$form_state){
	//dpm($form_state['values']);

	// regex for validating form
	$signed_degree_regex = '/^[+-]?\d+(\.\d+)?$/';

	// shorthand for long array names
	$lat = $form_state['values']['windfarms_default_center_lat'];
	$lon = $form_state['values']['windfarms_default_center_long'];

	//validate lat and lon format
	if(!preg_match($signed_degree_regex,$lat)){
		form_set_error('windfarms_default_center_long',t('invalid lat'));
	}
		if(!preg_match($signed_degree_regex,$lon)){
		form_set_error('windfarms_default_center_long',t('invalid lon'));
	}

	//validate lat and lon values
	if(!((-180<=$lat) && ($lat <= 180))){
		form_set_error('windfarms_default_center_lat',t('latidude cant be less than -180 or more than 180, yo'));
	}
		if(!((-180<=$lon) && ($lon = 180))){
		form_set_error('windfarms_default_center_long',t('longitude cant be less than -180 or more than 180, yo'));
	}

}

/**
 *Process a validated Wind Farm admin settings submission
 */
/*
function windfarms_admin_settings_form_submit($form,&$form_state){
// rebuild form
	$form_state['rebuild'] = TRUE;

	// save the variables
	variable_set('windfarms_gmap',$form_state['values']['windfarms_gmap']);
variable_set('windfarms_default_center_lat',$form_state['values']['windfarms_default_center_lat']);
variable_set('windfarms_default_center_long',$form_state['values']['windfarms_default_center_long']);
variable_set('windfarms_default_center_zoom',$form_state['values']['windfarms_default_center_zoom']);
//notify  user
drupal_set_message(t('wind farm settings saved.'));
}
*/
